AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Add restriction on S3 bucket to only allow download from AWS resources in the same region
  Needs to be periodically re-triggered because the IP address change.
  Data transfers within the same region between AWS resources are free.
  Restricts downloading files from this bucket to only AWS resources (e.g. EC2 , Lambda) within the same region as this bucket.
  This will not allow even the owner of the bucket to download objects in this bucket when not using an AWS resource in the same region!
Metadata:
  AWS::ServerlessRepo::Application:
    Name: "cfn-cr-same-region-bucket-download"
    Description: "Add restriction on S3 bucket to only allow download from AWS resources in the same region. Needs to be periodically re-triggered because the IP address change."
    Author: "Sage-Bionetworks"
    SpdxLicenseId: "Apache-2.0"
    # paths are relative to .aws-sam/build directory
    LicenseUrl: "LICENSE"
    ReadmeUrl: "README.md"
    Labels: ["serverless", "template", "github", "quick-start"]
    HomePageUrl: "https://github.com/Sage-Bionetworks-IT/cfn-cr-same-region-bucket-download"
    SemanticVersion: "0.0.1"
    SourceCodeUrl: "https://github.com/Sage-Bionetworks-IT/cfn-cr-same-region-bucket-download/tree/0.0.1"

Resources:
  RestrictBucketDownloadRegionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: external-bucket-lambda-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetBucketPolicy"
                  - "s3:PutBucketPolicy"
                  - "s3:DeleteBucketPolicy"
                Resource: "arn:aws:s3:::*"
        - PolicyName: PublishToCloudwatch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
  RestrictBucketDownloadRegionFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: Dynamically updates the external bucket policy to restrict downloading only IP addresses listed by AWS.
      Runtime: python3.7
      Handler: "restrict_download_region/restrict_region.handler"
      Role: !GetAtt RestrictBucketDownloadRegionRole.Arn
      Timeout: 30
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
  # subscribe to SNS provided by amazon to update group policy as they update
  # https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html
  BucketGroupPolicyUpdateSNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: 'arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged'
      Protocol: lambda
      Endpoint: !GetAtt RestrictBucketDownloadRegionFunction.Arn
  # for sns to trigger group policy update lambda
  BucketGroupPolicyUpdateLambdaSNSInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt RestrictBucketDownloadRegionFunction.Arn
      Action: 'lambda:InvokeFunction'
      SourceArn: 'arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged'
      Principal: sns.amazonaws.com

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RestrictBucketDownloadRegionFunctionName:
    Value: !Ref RestrictBucketDownloadRegionFunction
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-RestrictBucketDownloadRegionFunctionName"
  RestrictBucketDownloadRegionFunctionArn:
    Value: !GetAtt RestrictBucketDownloadRegionFunction.Arn
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-RestrictBucketDownloadRegionFunctionArn"
